version: "3.9"
name: "autonomous-car"
services:
  autonomous-car:
    build: ./
    image: autonomous-car:latest
    volumes:
      - .:/src
    tty: true
    command: /bin/bash
    container_name: autonomous-car
